# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = rofi -show run

#Enviornments
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exec, spotify-launcher
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = SUPER, SPACE, exec, rofi -show drun

# Workspaces 1-6
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6

# Move focused window to workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
# Shifting windows around
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
# Alt-Tab
bind = ALT, Tab, cyclenext
bind = ALT, Tab, bringactivetotop

# Move focused window around tiles
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Screenshots
bind = , Print, exec, mkdir -p ~/Pictures/Screenshots && grim ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && wl-copy < "$(ls -t ~/Pictures/Screenshots/*.png | head -n1)"

bind = SHIFT, Print, exec, mkdir -p ~/Pictures/Screenshots && grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png && wl-copy < "$(ls -t ~/Pictures/Screenshots/*.png | head -n1)"

# Volume
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Media playback
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPause, exec, playerctl pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous

# Brightness
bindel = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 10%-


# monitors
monitor=eDP-1,2560x1600@60,0x0,1.6
#monitor=DP-7,1920x1080@60,auto,1,mirror,eDP-1
#monitor=HDMI-A-2,1920x1080@60,auto,1,mirror,eDP-1

# Opening settings
exec-once = waybar &
#hyrpaper (wallpaper)
exec-once = hyprpaper


# Transparent Windows 
decoration {
    rounding = 12

    active_opacity = 0.85
    inactive_opacity = 0.75

    blur {
        enabled = true
        size = 2
        passes = 1
    }
}
# Getting rid of hyrland logos
disable_hyprland_logo = true
disable_splash_rendering = true

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# Lock screen
bind = SUPER, L, exec, hyprlock


# App launchers
bind = $mainMod, B, exec, brave
bind = $mainMod, C, exec, code
bind = $mainMod, S, exec, wlogout
bind = SUPER, E, exec, thunderbird

#Mouses
bind = , mouse:275, exec, wtype -M ctrl v -m ctrl
bind = , mouse:276, exec, wtype -M ctrl c -m ctrl



