background {
    monitor =
    path = /home/spotmccormick/Pictures/desktop_wallpaper/tux_tron.png

    blur_passes = 4
    blur_size = 8
    noise = 0.00
    contrast = 1.0
    brightness = 0.95
    vibrancy = 0.1
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%I:%M %p")"

    color = rgba(255,255,255,0.85)
    font_family = JetBrains Mono Nerd Font
    font_size = 80

    position = 0, 120
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d, %Y")"

    color = rgba(255,255,255,0.65)
    font_family = JetBrains Mono Nerd Font
    font_size = 24

    position = 0, 55
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 1

    outer_color = rgba(122,162,247,0.35)
    inner_color = rgba(0,0,0,0.20)
    font_color = rgb(255,255,255)

    font_family = JetBrains Mono Nerd Font

    rounding = 15
    fade_on_empty = false
    placeholder_text = Password...

    position = 0, -80
    halign = center
    valign = center
}
