preload = /home/spotmccormick/Pictures/desktop_wallpaper/sierras.png

wallpaper {
    monitor =
    path = /home/spotmccormick/Pictures/desktop_wallpaper/sierras.png
    fit_mode = cover
}

splash=false
ipc = on
