-- Generated by nwg-displays on 2026-06-03 at 11:29:33. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x09BA",
    mode = "2560x1600@60.0",
    position = "0x0",
    scale = 1.6
})
hl.monitor({
    output = "desc:Dell Inc. DELL P2722H 2SM8DJ3",
    mode = "1920x1080@60.0",
    position = "1600x0",
    scale = 1.0,
    mirror = "eDP-1"
})
