-- Generated by nwg-displays on 2026-06-02 at 15:09:53. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:BOE 0x09BA",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:BOE 0x09BA"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:BOE 0x09BA"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "desc:BOE 0x09BA"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "desc:BOE 0x09BA"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "desc:BOE 0x09BA"
})
